### ISSUE TITLE
exporter crashes

### ISSUE THREAD

**Issue by gzivdo** [qiangmzsx/bind_stats_exporter#1]
> Dec 14 12:37:44 test1 bind_stats_exporter[27243]: panic: runtime error: slice bounds out of range [:-1]
> Dec 14 12:37:44 test1 bind_stats_exporter[27243]: goroutine 43 [running]:
> Dec 14 12:37:44 test1 bind_stats_exporter[27243]: main.(*statsCollector).Collect(0xc0002249a0, 0xc000069760?)
> Dec 14 12:37:44 test1 bind_stats_exporter[27243]: bind-stats-exporter/bind_exporter_stats.go:464
>  +0xb19
> Dec 14 12:37:44 test1 bind_stats_exporter[27243]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
> Dec 14 12:37:44 test1 bind_stats_exporter[27243]:bind-stats-exporter/vendor/github.com/promethe
> us/client_golang/prometheus/registry.go:444 +0xfb
> Dec 14 12:37:44 test1 bind_stats_exporter[27243]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
> Dec 14 12:37:44 test1 bind_stats_exporter[27243]: bind-stats-exporter/vendor/github.com/promethe
> us/client_golang/prometheus/registry.go:536 +0xb0b
> Dec 14 12:37:44 test1 systemd[1]: bind_stats_exporter.service: main process exited, code=exited, status=2/INVALIDARGUMENT

It fails on that content:
++ Cache DB RRsets ++
[View: default]
                  70 A
                  11 NS
                   2 SOA
                  64 AAAA
                   5 DS
                  14 RRSIG
                   1 NSEC
                   2 DNSKEY
                   1 !NS
                   2 !AAAA
                   1 !DS
[View: _bind (Cache: _bind)]

**Comment by qiangmzsx** [comment]
Thanks for the feedback, it would be more helpful for me to troubleshoot the issue if you could post the contents page from the `--bind.stats-file=/var/named/named.stats` file.

**Comment by qiangmzsx** [comment]
If it's not convenient, you can do it at:
bind_exporter_stats_test.go to verify the content for the presence of panic;

**Comment by qiangmzsx** [comment]
I've made a version of the fix, you can verify to see if it's still panic. you can `git clone` or `git pull` to update and see.

**Comment by gzivdo** [comment]
thanks, its not crashes now
meanwhile, will the graphana template for original bind exporter work with it?

**Comment by qiangmzsx** [comment]
I don't think anyone has generated a template for it yet, you could try making one.
